pergunta01 = input('Telefonou para a vítima? ')
pergunta02 = input('Esteve no local? ')
pergunta03 = input('Mora perto da vítima? ')
pergunta04 = input('Devia para a vítima? ')
pergunta05 = input('Já trabalhou com a vítima? ')